### ISSUE TITLE
How to apply rules?

### ISSUE THREAD

**Issue by hrenki** [illsk1lls/ZipRipper#6] opened 2024-04-12 07:21 UTC
Is there any way to apply regex rules on password guess? eg. length and characters to use?

**Comment by SquidishXD** [comment] 2024-04-12 13:10
I don't believe so. It seems like it starts a brute force after awhile idk. (Note: not the programmer)

This is mine after 1 day cracking

Remaining hashes    1 (0 removed)
Remaining salts     1 (0 removed)
Time in seconds     80084.07 (1401.77 new)
Successful guesses  0 (0 new, 0 g/s)
Passwords tested    8921393152 (152764416 new, 108979 p/s)
  dupe suppressor    is enabled since accepted candidate 8767137793
  and it accepted    154370048 (95.90%, 108941 p/s)
         rejected    6605508 (4.10%, 4661 p/s)
     out of total    160975556 (113603 p/s)
Hash computations   8921393152 (152764416 new, 108979 c/s)
Hash combinations   8921393152 (152764416 new, 108979 C/s)

**Comment by illsk1lls** [comment] 2024-04-16 13:06
I am adding options for alternate wordlists first, then shortly thereafter optional rules

**Comment by lucasoares** [comment] 2024-04-26 15:52
> I am adding options for alternate wordlists first, then shortly thereafter optional rules

I know it is not related, but there is any way to disable GPU mode? My CPU keeps on 1% and GPU on 30~40%, 4200c/s, pretty bad for a 3070 and i9

Configuration rules should also be nice :P

**Comment by illsk1lls** [comment] 2024-05-01 01:20
what is the filetype you are testing against?

**Comment by lucasoares** [comment] 2024-05-03 01:13
> what is the filetype you are testing against?

`.rar`

**Comment by illsk1lls** [comment] 2024-05-07 13:08
Commenting out lines 321-325 (by adding REM to the front of each line with a space after) will disable GPU support for RAR files on the latest version of ZipRipper

**Comment by illsk1lls** [comment] 2024-05-10 04:35
alternate wordlists options is included now, click johns mouth to change wordlists

rules are next up as soon as i can find a way to squeeze them in the GUI is at its limits for a single line at present

**Comment by illsk1lls** [comment] 2024-09-13 12:12
I'm gonna to close this as an issue, and keep it in mind for future pushes.. As it is a feature request, not a bug.

**Closed by illsk1lls** 2024-09-13 12:12 UTC
Labels: enhancement
